# Generated by Django 6.0.6 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0001_initial"),
        ("users", "0002_freyjauser_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="employment.employee",
            ),
        ),
    ]
