# Generated by Django 6.0.6 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0003_move_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
