# Generated by Django 6.0.6 on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0004_employee_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="leave_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_approval_assignments",
                to="employment.employee",
            ),
        ),
    ]
