# Generated by Django 6.0.6 on 2026-08-03

from datetime import datetime, time, timedelta

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def migrate_leave_data(apps, schema_editor):
    Leave = apps.get_model("leaves", "Leave")
    Employee = apps.get_model("employment", "Employee")

    for leave in Leave.objects.select_related("employee__user"):
        employee = Employee.objects.filter(user_id=leave.employee.user_id).first()
        if employee is None:
            continue

        start_datetime = datetime.combine(leave.start_date, time(hour=9))
        end_datetime = datetime.combine(leave.end_date, time(hour=17))
        if timezone.is_aware(timezone.now()):
            start_datetime = timezone.make_aware(start_datetime)
            end_datetime = timezone.make_aware(end_datetime)

        leave.request_employee_id = employee.id
        leave.request_start_datetime = start_datetime
        leave.request_end_datetime = end_datetime
        leave.comment = leave.reason
        leave.approver_id = employee.leave_approver_id or employee.manager_id
        leave.save(
            update_fields=(
                "request_employee",
                "request_start_datetime",
                "request_end_datetime",
                "comment",
                "approver",
            )
        )

    Leave.objects.filter(request_employee__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0005_employee_leave_approver"),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_requests_to_approve",
                to="employment.employee",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leave",
            name="request_employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="employment.employee",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="request_end_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="request_start_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(migrate_leave_data, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="leave",
            name="leave_end_date_on_or_after_start_date",
        ),
        migrations.RemoveField(model_name="leave", name="employee"),
        migrations.RemoveField(model_name="leave", name="end_date"),
        migrations.RemoveField(model_name="leave", name="reason"),
        migrations.RemoveField(model_name="leave", name="start_date"),
        migrations.RenameField(
            model_name="leave",
            old_name="request_employee",
            new_name="employee",
        ),
        migrations.RenameField(
            model_name="leave",
            old_name="request_end_datetime",
            new_name="end_datetime",
        ),
        migrations.RenameField(
            model_name="leave",
            old_name="request_start_datetime",
            new_name="start_datetime",
        ),
        migrations.AlterField(
            model_name="leave",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="employment.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="end_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.IntegerField(
                choices=[
                    (1, "Annual"),
                    (2, "Sick"),
                    (3, "Unpaid"),
                    (4, "Other"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="leave",
            name="start_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name="leave",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    end_datetime__gte=models.F("start_datetime") + timedelta(hours=4)
                ),
                name="leave_period_at_least_four_hours",
            ),
        ),
        migrations.AlterModelOptions(
            name="leave",
            options={"ordering": ("-start_datetime", "-created_at")},
        ),
    ]
