# Generated by Django 6.0.6 on 2026-08-04

from django.db import migrations, models


def migrate_datetime_periods(apps, schema_editor):
    Leave = apps.get_model("leaves", "Leave")

    for leave in Leave.objects.all():
        start = leave.start_datetime
        end = leave.end_datetime
        leave.request_start_date = start.date()
        leave.request_end_date = end.date()

        if start.date() == end.date() and (end - start).total_seconds() <= 4 * 60 * 60:
            day_part = "first_half" if start.hour < 12 else "second_half"
            leave.start_day_part = day_part
            leave.end_day_part = day_part
        else:
            leave.start_day_part = "second_half" if start.hour >= 12 else "full_day"
            leave.end_day_part = "first_half" if end.hour <= 13 else "full_day"

        leave.save(
            update_fields=(
                "request_start_date",
                "request_end_date",
                "start_day_part",
                "end_day_part",
            )
        )


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0002_leave_request_mvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="start_day_part",
            field=models.CharField(
                choices=[
                    ("full_day", "Full day"),
                    ("first_half", "First half"),
                    ("second_half", "Second half"),
                ],
                default="full_day",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="end_day_part",
            field=models.CharField(
                choices=[
                    ("full_day", "Full day"),
                    ("first_half", "First half"),
                    ("second_half", "Second half"),
                ],
                default="full_day",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="request_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="request_end_date",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(migrate_datetime_periods, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="leave",
            name="leave_period_at_least_four_hours",
        ),
        migrations.RemoveField(model_name="leave", name="start_datetime"),
        migrations.RemoveField(model_name="leave", name="end_datetime"),
        migrations.RenameField(
            model_name="leave",
            old_name="request_start_date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="leave",
            old_name="request_end_date",
            new_name="end_date",
        ),
        migrations.AlterField(
            model_name="leave",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leave",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="leave",
            constraint=models.CheckConstraint(
                condition=models.Q(end_date__gte=models.F("start_date")),
                name="leave_end_date_on_or_after_start_date",
            ),
        ),
        migrations.AlterModelOptions(
            name="leave",
            options={"ordering": ("-start_date", "-created_at")},
        ),
    ]
