# Generated by Django 6.0.6 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0003_leave_day_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
