# Generated by Django 6.0.6 on 2026-07-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0003_move_user_managers"),
        ("users", "0002_freyjauser_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freyjauser",
            name="manager",
        ),
    ]
